### ISSUE TITLE
Enforce Python conventions

### ISSUE THREAD

**Issue by felipeZ** [votca/PyVOTCA#19]
## Goal
Follows Python convention about naming

## TODO
* [x] rename the library to lowercase 
* [x] Use camelcase for Classes
* [x] Use snakecase for methods and functions
* [x] Use uppercase for constants
* [x] Follow functions,methods and classes documentation conventions
* [x] Add [mypy](http://mypy-lang.org/) test
